<a href="https://colab.research.google.com/github/Gen54cw/Analitica-de-Datos-Tintaya-Daniel/blob/main/laboratorios/LAB01_TintayaDaniel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio 1: Evaluación de factibilidad de un caso de uso analítico

Alumno: Tintaya Avila Daniel Eduardo

Codigo: 21200032

Fecha: 26/08/2026

# Paso 1. Configuración del entorno

In [3]:
import pandas as pd
import numpy as np
import unicodedata
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)
print("pandas:", pd.__version__)
print("numpy :", np.__version__)

pandas: 2.2.3
numpy : 2.1.3

Las versiones utilizadas en el notebook corresponden a:

pandas: 2.2.3

numpy: 2.1.3

# Paso 2 · Carga e inventario inicial

In [4]:
citas = pd.read_csv("citas_red_salud.csv", encoding="utf-8")
sedes = pd.read_csv("catalogo_sedes.csv", encoding="utf-8")
print("citas :", citas.shape)
print("sedes :", sedes.shape)
print()
citas.info()
display(citas.head(5))
display(sedes)

citas : (12200, 20)
sedes : (14, 6)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12200 entries, 0 to 12199
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_cita                 12200 non-null  object
 1   id_paciente             12200 non-null  object
 2   sede                    12200 non-null  object
 3   distrito                11467 non-null  object
 4   especialidad            12055 non-null  object
 5   fecha_programacion      12200 non-null  object
 6   fecha_cita              12200 non-null  object
 7   hora_cita               12200 non-null  object
 8   canal_agendamiento      11652 non-null  object
 9   dias_anticipacion       11933 non-null  float64
 10  edad_paciente           11854 non-null  float64
 11  citas_previas           12200 non-null  int64
 12  inasistencias_previas   12200 non-null  int64
 13  telefono_confirmado     4586 non-null   object
 14  diagnostico_cie10       12200 non-null  object
 15  estado_cita             12200 non-null  object
 16  fecha_cancelacion       1352 non-null   object
 17  hora_registro_atencion  7231 non-null   object
 18  duracion_atencion_min   7231 non-null   float64
 19  motivo_no_asistencia    3617 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 1.9+ MB

/usr/local/lib/python3.13/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,id_cita,id_paciente,sede,distrito,especialidad,fecha_programacion,fecha_cita,hora_cita,canal_agendamiento,dias_anticipacion,edad_paciente,citas_previas,inasistencias_previas,telefono_confirmado,diagnostico_cie10,estado_cita,fecha_cancelacion,hora_registro_atencion,duracion_atencion_min,motivo_no_asistencia
0,C2407125,P146731,CAP San Martín de Porres,San Martín de Porres,Cardiología,2025-06-11,2025-07-15,09:15,App,34.0,24.0,7,2,NaN,L20.9,Cancelada,2025-06-26,NaN,NaN,NaN
1,C2400808,P122053,CAP Surquillo,Surquillo,Ginecología,2025-08-20,01/09/2025,08:00,Telefonico,12.0,66.0,2,2,Si,E78.5,Atendida,NaN,08:00,6.0,NaN
2,C2401689,P142968,CAP Independencia,Independencia,Dermatología,2026-01-07,2026-01-14,10:45,Presencial,7.0,33.0,4,1,No,G43.9,Cancelada,2026-01-08,NaN,NaN,NaN
3,C2410000,P101367,CAP Santa Anita,Santa Anita,Endocrinología,2025-10-30,2025-12-01,11:30,app movil,32.0,4.0,9,2,NaN,J45,Atendida,NaN,11:13,14.0,NaN
4,C2401784,P116873,CAP Puente Piedra,Puente Piedra,Odontología,2024-11-02,2024-11-14,16:15,Web,12.0,50.0,5,1,NaN,E11.9,Atendida,NaN,16:40,10.0,NaN

,sede,distrito,nivel_establecimiento,consultorios_ambulatorios,anio_apertura,horas_medico_semana
0,CAP San Juan de Lurigancho,San Juan de Lurigancho,I-4,22,2009,980
1,CAP Comas,Comas,I-4,18,2011,810
2,CAP Villa El Salvador,Villa El Salvador,I-3,14,2014,640
3,CAP Ate,Ate,I-4,19,2010,850
4,CAP San Martin de Porres,San Martín de Porres,I-3,15,2013,690
5,CAP Callao,Callao,II-1,26,2006,1180
6,CAP Los Olivos,Los Olivos,I-4,17,2012,760
7,CAP Chorrillos,Chorrillos,I-3,13,2015,590
8,CAP Santa Anita,Santa Anita,I-3,12,2016,545
9,CAP Puente Piedra,Puente Piedra,I-3,11,2017,500
10,CAP Independencia,Independencia,I-4,16,2012,720
11,CAP El Agustino,El Agustino,I-3,12,2015,540
12,CAP Surquillo,Surquillo,II-1,24,2008,1060
13,CAP Lince,Lince,I-4,15,2011,670

**Preguntas**

**2.1 ¿Cuántas filas y cuántas columnas tiene cada archivo?**

citas:  12200 filas y 20 columnas

sedes: 14 filas y 6 columnas

2.2 ¿Qué columnas deberían ser numéricas o de fecha pero llegaron como texto? Enumérelas.


*   fecha_programacion
*   fecha_cita
*   hora_cita
*   fecha_cancelacion
*   hora_registro_atencion

Estas columnas no deben ser consideradas como texto


**2.3 A partir de los nombres de las columnas y de las primeras filas, ¿cuál cree que es la granularidad del archivo principal, es decir, qué representa una fila?**

La fila representa una cita programada de un paciente en una sede determinada, además de contener información relacionada con la programación de la cita, el paciente y el estado final de la cita.

# Paso 3 · Diccionario de datos

## Diccionario de datos

| Variable | Significado | Tipo esperado |
|---|---|---|
| `id_cita` | Identificador de la cita programada. Debería ser único. | Texto (clave) |
| `id_paciente` | Identificador del paciente. Se repite entre citas. | Texto (clave foránea) |
| `sede` | Establecimiento donde se programó la atención. | Categórica |
| `distrito` | Distrito del establecimiento. | Categórica |
| `especialidad` | Especialidad médica de la cita. | Categórica |
| `fecha_programacion` | Fecha en que se agendó la cita. | Fecha |
| `fecha_cita` | Fecha para la que se programó la atención. | Fecha |
| `hora_cita` | Hora programada de la atención. | Hora |
| `canal_agendamiento` | Medio por el que se agendó: presencial, teléfono, app o web. | Categórica |
| `dias_anticipacion` | Días entre el agendamiento y la cita, según el sistema. | Entero ≥ 0 |
| `edad_paciente` | Edad del paciente en años. | Entero, 0 a 110 |
| `citas_previas` | Número de citas históricas del paciente en la red. | Entero ≥ 0 |
| `inasistencias_previas` | Número de inasistencias históricas del paciente. | Entero ≥ 0 |
| `telefono_confirmado` | Si el teléfono de contacto fue verificado. | Categórica (Si/No) |
| `diagnostico_cie10` | Código de diagnóstico asociado a la atención. | Categórica |
| `estado_cita` | Estado final: Atendida, No atendida o Cancelada. | Categórica |
| `fecha_cancelacion` | Fecha en que el paciente canceló, si canceló. | Fecha |
| `hora_registro_atencion` | Hora en que se registró el ingreso del paciente al consultorio. | Hora |
| `duracion_atencion_min` | Duración de la consulta en minutos. | Entero |
| `motivo_no_asistencia` | Motivo registrado cuando el paciente no se presentó. | Categórica |

In [5]:
categoricas = ["sede", "distrito", "especialidad", "canal_agendamiento",
 "estado_cita", "telefono_confirmado"]
for col in categoricas:
 print("=" * 60)
 print(col, "->", citas[col].nunique(dropna=True), "valores distintos")
 print(citas[col].value_counts(dropna=False).head(12))

============================================================
sede -> 30 valores distintos
sede
CAP Ate                       877
CAP Santa Anita               871
CAP San Martín de Porres      853
CAP Lince                     851
CAP El Agustino               848
CAP Villa El Salvador         838
CAP San Juan de Lurigancho    837
CAP Chorrillos                837
CAP Surquillo                 834
CAP Callao                    829
CAP Los Olivos                824
CAP Puente Piedra             819
Name: count, dtype: int64
============================================================
distrito -> 14 valores distintos
distrito
Ate                       855
Lince                     839
Santa Anita               835
Villa El Salvador         832
San Martín de Porres      824
San Juan de Lurigancho    822
El Agustino               820
Chorrillos                815
Puente Piedra             813
Surquillo                 810
Callao                    806
Los Olivos                803
Name: count, dtype: int64
============================================================
especialidad -> 30 valores distintos
especialidad
Odontología         1175
Oftalmología        1119
Neurología          1110
Cardiología         1104
Endocrinología      1084
Ginecología         1082
Dermatología        1073
Medicina General    1073
Traumatología       1065
Pediatría           1043
NaN                  145
DERMATOLOGÍA          86
Name: count, dtype: int64
============================================================
canal_agendamiento -> 6 valores distintos
canal_agendamiento
Presencial    3685
Telefonico    2879
App           2445
Web           2070
NaN            548
PRESENCIAL     339
app movil      234
Name: count, dtype: int64
============================================================
estado_cita -> 5 valores distintos
estado_cita
Atendida       6949
No atendida    3469
Cancelada      1296
ATENDIDA        303
no atendida     183
Name: count, dtype: int64
============================================================
telefono_confirmado -> 2 valores distintos
telefono_confirmado
NaN    7614
No     2337
Si     2249
Name: count, dtype: int64

**RESPUESTA PASO 3**

**3.1 La red tiene catorce sedes y diez especialidades. ¿Cuántos valores distintos reporta el archivo para esas dos columnas? ¿Cómo se explica la diferencia?**



**3.2 Identifique al menos tres formas en que un mismo valor aparece escrito de manera distinta.**


**3.3 ¿Qué columna tiene una proporción de valores faltantes tan alta que probablemente no sea utilizable? Justifique.**